# Generated by Django 3.1.7 on 2021-05-17 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0004_matches'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matches',
            name='result',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='WebApp.team'),
        ),
    ]
