# Generated by Django 3.1.7 on 2021-05-17 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0005_auto_20210517_1750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matches',
            name='team1_overs',
        ),
        migrations.RemoveField(
            model_name='matches',
            name='team1_score',
        ),
        migrations.RemoveField(
            model_name='matches',
            name='team2_overs',
        ),
        migrations.RemoveField(
            model_name='matches',
            name='team2_score',
        ),
    ]
